In [9]:
import pandas as pd

In [11]:
titlesdfless = pd.read_csv(r"C:\Users\tyto4\OneDrive\Dokumente\0_Winfo_MA\SS22_IR\IR_Netflix_TVShows_Movies_VAD\Data\AufbereiteteDaten\titleslessdf.csv", sep=',')

In [12]:
titlesdfless

,Unnamed: 0,id,title,type,release_year,runtime,genres,production_countries,seasons,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,0,ts300399,Five Came Back: The Reference Films,SHOW,1945,48,['documentation'],['US'],1.0,NaN,NaN,0.600,NaN
1,1,tm84618,Taxi Driver,MOVIE,1976,113,"['crime', 'drama']",['US'],NaN,8.3,795222.0,27.612,8.2
2,2,tm127384,Monty Python and the Holy Grail,MOVIE,1975,91,"['comedy', 'fantasy']",['GB'],NaN,8.2,530877.0,18.216,7.8
3,3,tm70993,Life of Brian,MOVIE,1979,94,['comedy'],['GB'],NaN,8.0,392419.0,17.505,7.8
4,4,tm190788,The Exorcist,MOVIE,1973,133,['horror'],['US'],NaN,8.1,391942.0,95.337,7.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5801,5801,tm1014599,Fine Wine,MOVIE,2021,100,"['romance', 'drama']",['NG'],NaN,6.9,39.0,0.966,NaN
5802,5802,tm1108171,Edis Starlight,MOVIE,2021,74,"['music', 'documentation']",[],NaN,NaN,NaN,1.036,8.5
5803,5803,tm1045018,Clash,MOVIE,2021,88,"['family', 'drama']","['NG', 'CA']",NaN,6.5,32.0,0.709,NaN
5804,5804,tm1098060,Shadow Parties,MOVIE,2021,116,"['action', 'thriller']",[],NaN,6.2,9.0,2.186,NaN
5805,5805,ts271048,Mighty Little Bheem: Kite Festival,SHOW,2021,0,"['family', 'comedy', 'animation']",[],1.0,8.8,16.0,0.979,10.0

In [13]:
titlesdfless=titlesdfless.dropna(subset=["id","title","type","release_year","runtime","imdb_score","imdb_votes"])

In [14]:
titlesdfless.to_csv(r"C:\Users\tyto4\OneDrive\Dokumente\0_Winfo_MA\SS22_IR\IR_Netflix_TVShows_Movies_VAD\Data\AufbereiteteDaten\titleslessdf1.csv",sep=",")